import jsPDF from 'jspdf';

export interface PayrollSummaryData {
  period: {
    name: string;
    startDate: string;
    endDate: string;
    payDate: string;
  };
  totals: {
    employees: number;
    grossPay: number;
    deductions: number;
    netPay: number;
  };
  employees: Array<{
    name: string;
    employeeNumber: string;
    regularHours: number;
    overtimeHours: number;
    regularPay: number;
    overtimePay: number;
    grossPay: number;
    totalDeductions: number;
    netPay: number;
  }>;
  company: {
    name: string;
    address?: string;
  };
}

export const generatePayrollPDF = (data: PayrollSummaryData): void => {
  const doc = new jsPDF();
  
  // Header
  doc.setFontSize(18);
  doc.text(data.company.name, 20, 20);
  doc.setFontSize(14);
  doc.text('Payroll Summary Report', 20, 30);
  
  // Period Information
  doc.setFontSize(10);
  doc.text(`Pay Period: ${data.period.name}`, 20, 45);
  doc.text(`Period: ${new Date(data.period.startDate).toLocaleDateString()} - ${new Date(data.period.endDate).toLocaleDateString()}`, 20, 52);
  doc.text(`Pay Date: ${new Date(data.period.payDate).toLocaleDateString()}`, 20, 59);
  doc.text(`Generated: ${new Date().toLocaleDateString()} ${new Date().toLocaleTimeString()}`, 20, 66);
  
  // Summary Totals
  doc.setFontSize(12);
  doc.text('Summary', 20, 80);
  doc.setFontSize(10);
  doc.text(`Total Employees: ${data.totals.employees}`, 20, 90);
  doc.text(`Total Gross Pay: R${data.totals.grossPay.toFixed(2)}`, 20, 97);
  doc.text(`Total Deductions: R${data.totals.deductions.toFixed(2)}`, 20, 104);
  doc.text(`Total Net Pay: R${data.totals.netPay.toFixed(2)}`, 20, 111);
  
  // Employee Details Header
  let yPosition = 130;
  doc.setFontSize(12);
  doc.text('Employee Details', 20, yPosition);
  yPosition += 10;
  
  // Table Header
  doc.setFontSize(8);
  doc.text('Employee', 20, yPosition);
  doc.text('Emp #', 60, yPosition);
  doc.text('Reg Hrs', 85, yPosition);
  doc.text('OT Hrs', 105, yPosition);
  doc.text('Gross Pay', 125, yPosition);
  doc.text('Deductions', 150, yPosition);
  doc.text('Net Pay', 175, yPosition);
  
  // Draw line under header
  doc.line(20, yPosition + 2, 190, yPosition + 2);
  yPosition += 8;
  
  // Employee rows
  data.employees.forEach((employee) => {
    if (yPosition > 270) { // Start new page if needed
      doc.addPage();
      yPosition = 20;
    }
    
    doc.text(employee.name.substring(0, 18), 20, yPosition);
    doc.text(employee.employeeNumber, 60, yPosition);
    doc.text(employee.regularHours.toString(), 85, yPosition);
    doc.text(employee.overtimeHours.toString(), 105, yPosition);
    doc.text(`R${employee.grossPay.toFixed(2)}`, 125, yPosition);
    doc.text(`R${employee.totalDeductions.toFixed(2)}`, 150, yPosition);
    doc.text(`R${employee.netPay.toFixed(2)}`, 175, yPosition);
    
    yPosition += 7;
  });
  
  // Footer
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.text(`Page ${i} of ${pageCount}`, 20, 285);
    doc.text('Generated by Factory Management System', 140, 285);
  }
  
  // Download
  doc.save(`payroll-summary-${data.period.name.replace(/\s+/g, '-').toLowerCase()}.pdf`);
};

export const generateIndividualPayslip = (employeeData: {
  employee: {
    name: string;
    employeeNumber: string;
    department: string;
    position?: string;
  };
  period: {
    name: string;
    startDate: string;
    endDate: string;
    payDate: string;
  };
  payroll: {
    regularHours: number;
    overtimeHours: number;
    regularPay: number;
    overtimePay: number;
    grossPay: number;
    deductions: Array<{ name: string; amount: number }>;
    totalDeductions: number;
    netPay: number;
  };
  company: {
    name: string;
    address?: string;
  };
}): void => {
  const doc = new jsPDF();
  
  // Header
  doc.setFontSize(16);
  doc.text(employeeData.company.name, 20, 20);
  doc.setFontSize(14);
  doc.text('Payslip', 20, 30);
  
  // Employee Info
  doc.setFontSize(10);
  doc.text(`Employee: ${employeeData.employee.name}`, 20, 45);
  doc.text(`Employee Number: ${employeeData.employee.employeeNumber}`, 20, 52);
  doc.text(`Department: ${employeeData.employee.department}`, 20, 59);
  if (employeeData.employee.position) {
    doc.text(`Position: ${employeeData.employee.position}`, 20, 66);
  }
  
  // Period Info
  doc.text(`Pay Period: ${employeeData.period.name}`, 120, 45);
  doc.text(`Period: ${new Date(employeeData.period.startDate).toLocaleDateString()} - ${new Date(employeeData.period.endDate).toLocaleDateString()}`, 120, 52);
  doc.text(`Pay Date: ${new Date(employeeData.period.payDate).toLocaleDateString()}`, 120, 59);
  
  // Earnings
  let yPos = 85;
  doc.setFontSize(12);
  doc.text('Earnings', 20, yPos);
  yPos += 10;
  
  doc.setFontSize(10);
  doc.text('Description', 20, yPos);
  doc.text('Hours', 80, yPos);
  doc.text('Amount', 120, yPos);
  doc.line(20, yPos + 2, 150, yPos + 2);
  yPos += 8;
  
  doc.text('Regular Pay', 20, yPos);
  doc.text(employeeData.payroll.regularHours.toString(), 80, yPos);
  doc.text(`R${employeeData.payroll.regularPay.toFixed(2)}`, 120, yPos);
  yPos += 7;
  
  if (employeeData.payroll.overtimeHours > 0) {
    doc.text('Overtime Pay', 20, yPos);
    doc.text(employeeData.payroll.overtimeHours.toString(), 80, yPos);
    doc.text(`R${employeeData.payroll.overtimePay.toFixed(2)}`, 120, yPos);
    yPos += 7;
  }
  
  doc.line(20, yPos, 150, yPos);
  yPos += 5;
  doc.text('Gross Pay:', 20, yPos);
  doc.text(`R${employeeData.payroll.grossPay.toFixed(2)}`, 120, yPos);
  yPos += 15;
  
  // Deductions
  if (employeeData.payroll.deductions.length > 0) {
    doc.setFontSize(12);
    doc.text('Deductions', 20, yPos);
    yPos += 10;
    
    doc.setFontSize(10);
    doc.text('Description', 20, yPos);
    doc.text('Amount', 120, yPos);
    doc.line(20, yPos + 2, 150, yPos + 2);
    yPos += 8;
    
    employeeData.payroll.deductions.forEach((deduction) => {
      doc.text(deduction.name, 20, yPos);
      doc.text(`R${deduction.amount.toFixed(2)}`, 120, yPos);
      yPos += 7;
    });
    
    doc.line(20, yPos, 150, yPos);
    yPos += 5;
    doc.text('Total Deductions:', 20, yPos);
    doc.text(`R${employeeData.payroll.totalDeductions.toFixed(2)}`, 120, yPos);
    yPos += 15;
  }
  
  // Net Pay
  doc.setFontSize(12);
  doc.text('NET PAY:', 20, yPos);
  doc.text(`R${employeeData.payroll.netPay.toFixed(2)}`, 120, yPos);
  
  // Footer
  doc.setFontSize(8);
  doc.text(`Generated: ${new Date().toLocaleDateString()} ${new Date().toLocaleTimeString()}`, 20, 280);
  
  // Download
  const fileName = `payslip-${employeeData.employee.employeeNumber}-${employeeData.period.name.replace(/\s+/g, '-').toLowerCase()}.pdf`;
  doc.save(fileName);
};