-- Insert missing employees from the second staff list
INSERT INTO employees (
    first_name, last_name, department, atg_clock_number, employee_number, 
    hourly_rate, employment_type, employee_type, is_active, factory
) VALUES 
-- Missing employees from the second list
('SIPHIWE', 'MOFULANI', 'UNIT 1 / PRINTING', '29', 'EMP0029', 28.79, 'full-time', 'permanent', true, 'Main Factory'),
('NTOMBOMZI', 'MBIKO', 'UNIT 3', '30', 'EMP0030', 28.79, 'full-time', 'permanent', true, 'Main Factory'),
('BONANI', 'TYITYI', 'REEL TO REEL', '43', 'EMP0043', 33.41, 'full-time', 'permanent', true, 'Main Factory'),
('WONDERBOY', 'UNKNOWN', 'BAILING', '44', 'EMP0044', 28.79, 'full-time', 'permanent', true, 'Main Factory'),
('ANITHA', 'MZOBOSHE', 'UNIT 6', '64', 'EMP0064', 28.79, 'full-time', 'permanent', true, 'Main Factory'),
('TABISA', 'TSEWU', 'UNIT 6', '69', 'EMP0069', 28.79, 'full-time', 'permanent', true, 'Main Factory'),
('ANATHI', 'GANGATHELE', 'UNIT 1', '71', 'EMP0071', 28.79, 'full-time', 'permanent', true, 'Main Factory'),
('BUKELWA', 'GAZITE', 'CUTTING', '78', 'EMP0078', 28.79, 'full-time', 'permanent', true, 'Main Factory'),
('BUKEKA', 'WELANI', 'CUTTING', '90', 'EMP0090', 28.79, 'full-time', 'permanent', true, 'Main Factory'),
('THABISA', 'ZAWE', 'UNIT 1', '109', 'EMP0109', 28.79, 'full-time', 'permanent', true, 'Main Factory'),
('WANDISA', 'HELWANA', 'LOOMS', '118', 'EMP0118', 0.00, 'full-time', 'permanent', true, 'Main Factory'),
('ABONGILE', 'NOTYANDELA', 'EXTRUDER', '207', 'EMP0207', 28.79, 'full-time', 'permanent', true, 'Main Factory'),
('ZIMKHITHA', 'MDLELENI', 'LOOMS', '221', 'EMP0221', 0.00, 'full-time', 'permanent', true, 'Main Factory'),
('UNATHI', 'JEKE', 'EXTRUDER', '223', 'EMP0223', 30.64, 'full-time', 'permanent', true, 'Main Factory'),
('NWABISA', 'MONA', 'EXTRUDER', '227', 'EMP0227', 28.79, 'full-time', 'permanent', true, 'Main Factory'),
('ASANDA', 'WAKENI', 'EXTRUDER', '229', 'EMP0229', 28.79, 'full-time', 'permanent', true, 'Main Factory'),
('GOODWILL', 'NGANGALALA', 'EXTRUDER', '234', 'EMP0234', 37.08, 'full-time', 'permanent', true, 'Main Factory'),
('MANDISI', 'FEKADE', 'MECHANIC TRAINING', '300', 'EMP0300', 35.00, 'full-time', 'permanent', true, 'Main Factory'),
('AVIWE', 'MAFOJELA', 'LOOMS', '302', 'EMP0302', 0.00, 'full-time', 'permanent', true, 'Main Factory'),
('NOLOYISO', 'MARANGXA', 'LOOMS', '303', 'EMP0303', 28.79, 'full-time', 'permanent', true, 'Main Factory'),
('ASANDA', 'MTATASE', 'LOOMS', '306', 'EMP0306', 0.00, 'full-time', 'permanent', true, 'Main Factory'),
('ZANDI PRETTY', 'SIMANGA', 'LOOMS', '307', 'EMP0307', 0.00, 'full-time', 'permanent', true, 'Main Factory'),
('THANDEKA', 'MVELELI', 'LOOMS', '308', 'EMP0308', 0.00, 'full-time', 'permanent', true, 'Main Factory'),
('NOMATHAMSANGA', 'NDUDULA', 'LOOMS', '310', 'EMP0310', 0.00, 'full-time', 'permanent', true, 'Main Factory'),
('NATHI', 'MAHASANA', 'LOOMS', '311', 'EMP0311', 0.00, 'full-time', 'permanent', true, 'Main Factory'),
('BUKELWA', 'MATHISO', 'LOOMS', '312', 'EMP0312', 0.00, 'full-time', 'permanent', true, 'Main Factory'),
('NOSIPHIWO', 'NELANI', 'LOOMS', '313', 'EMP0313', 31.32, 'full-time', 'permanent', true, 'Main Factory'),
('LINDA', 'MOLOBELI', 'BB BURNER NIG', '316', 'EMP0316', 14.83, 'full-time', 'permanent', true, 'Main Factory'),
('KOLOSA', 'MAJANGAZA', 'LOOMS', '317', 'EMP0317', 0.00, 'full-time', 'permanent', true, 'Main Factory'),
('ZINTLE', 'JAKAVULA', 'EXTRUDER', '319', 'EMP0319', 30.00, 'full-time', 'permanent', true, 'Main Factory'),
('XOLA', 'MAY', 'LOOMS', '322', 'EMP0322', 28.79, 'full-time', 'permanent', true, 'Main Factory'),
('SAKHUMZI', 'MABINDISA', 'EXTRUDER', '325', 'EMP0325', 28.79, 'full-time', 'permanent', true, 'Main Factory'),
('APIWE', 'NXEBA', 'LOOMS', '327', 'EMP0327', 14.83, 'full-time', 'permanent', true, 'Main Factory'),
('BULISWA', 'TSOBINI', 'LOOMS', '328', 'EMP0328', 0.00, 'full-time', 'permanent', true, 'Main Factory'),
('AYABONGA', 'PONTI', 'LOOMS', '329', 'EMP0329', 0.00, 'full-time', 'permanent', true, 'Main Factory'),
('SANDISIWE', 'MUKWA', 'LOOMS', '330', 'EMP0330', 0.00, 'full-time', 'permanent', true, 'Main Factory'),
('NOMFANELO', 'MZWELI', 'LOOMS', '331', 'EMP0331', 0.00, 'full-time', 'permanent', true, 'Main Factory'),
('SIZPHIWE', 'DANGAZELE', 'LOOMS', '332', 'EMP0332', 0.00, 'full-time', 'permanent', true, 'Main Factory'),
('PHELOKAZI', 'NGCWEMBE', 'LOOMS', '333', 'EMP0333', 0.00, 'full-time', 'permanent', true, 'Main Factory'),
('VIVIAN', 'BHOBHO', 'LOOMS', '335', 'EMP0335', 28.79, 'full-time', 'permanent', true, 'Main Factory'),
('BUNTU', 'PIKOKO', 'LOOMS', '336', 'EMP0336', 0.00, 'full-time', 'permanent', true, 'Main Factory'),
('NASIPHE', 'MPONDO', 'LOOMS', '337', 'EMP0337', 0.00, 'full-time', 'permanent', true, 'Main Factory'),
('BUSISWA', 'NTLANINGE', 'LOOMS', '338', 'EMP0338', 0.00, 'full-time', 'permanent', true, 'Main Factory'),
('SIYAMTHANDA', 'NGWENYA', 'LOOMS', '340', 'EMP0340', 0.00, 'full-time', 'permanent', true, 'Main Factory'),
('ANELISIWE', 'JONI', 'LOOMS', '341', 'EMP0341', 0.00, 'full-time', 'permanent', true, 'Main Factory'),
('LUSANDA', 'MZUKWA', 'LOOMS', '342', 'EMP0342', 0.00, 'full-time', 'permanent', true, 'Main Factory'),
('SINALO', 'MKWELO', 'LOOMS', '344', 'EMP0344', 0.00, 'full-time', 'permanent', true, 'Main Factory'),
('LUMKA', 'NTLIKITHI', 'LOOMS', '346', 'EMP0346', 0.00, 'full-time', 'permanent', true, 'Main Factory'),
('MTHUTHUZELI', 'MNQENQELE', 'LOOMS', '347', 'EMP0347', 28.79, 'full-time', 'permanent', true, 'Main Factory'),
('ZOLELWA', 'MPEPHO', 'BB BURNER', '348', 'EMP0348', 14.83, 'full-time', 'permanent', true, 'Main Factory'),
('LOVENESS', 'UNKNOWN', 'LOOMS', '350', 'EMP0350', 0.00, 'full-time', 'permanent', true, 'Main Factory'),
('SISANDA', 'SIHLANGULA', 'LOOMS', '352', 'EMP0352', 0.00, 'full-time', 'permanent', true, 'Main Factory'),
('NOSIPHE', 'SIZIBA', 'LOOMS', '353', 'EMP0353', 0.00, 'full-time', 'permanent', true, 'Main Factory'),
('ANDISWA', 'ZENZISI', 'LOOMS', '354', 'EMP0354', 0.00, 'full-time', 'permanent', true, 'Main Factory'),
('AMANDA', 'SOLWANDLE', 'LOOMS', '357', 'EMP0357', 28.79, 'full-time', 'permanent', true, 'Main Factory'),
('ASIVE', 'QWABE', 'LOOMS', '358', 'EMP0358', 28.79, 'full-time', 'permanent', true, 'Main Factory'),
('SIBONGILE', 'MBASA', 'LOOMS', '361', 'EMP0361', 0.00, 'full-time', 'permanent', true, 'Main Factory'),
('ZIOLISWA', 'NTATYANA', 'LOOMS', '363', 'EMP0363', 0.00, 'full-time', 'permanent', true, 'Main Factory'),
('PAMELLA', 'NKONJANE', 'LOOMS', '364', 'EMP0364', 0.00, 'full-time', 'permanent', true, 'Main Factory'),
('FEZEKA', 'ZWAKALA', 'LOOMS', '365', 'EMP0365', 0.00, 'full-time', 'permanent', true, 'Main Factory'),
('SANELE', 'SIRAYI', 'LOOMS', '369', 'EMP0369', 0.00, 'full-time', 'permanent', true, 'Main Factory'),
('ANATHI', 'NKONGO', 'LOOMS QLTY', '370', 'EMP0370', 16.50, 'full-time', 'permanent', true, 'Main Factory'),
('ZIKHONA', 'SINONI', 'LOOMS CLEAN', '371', 'EMP0371', 14.83, 'full-time', 'permanent', true, 'Main Factory'),
('ASANDA', 'MAHLANYANA', 'LOOMS', '374', 'EMP0374', 28.79, 'full-time', 'permanent', true, 'Main Factory'),
('THOMAS', 'NGXAMILE', 'LOOMS', '380', 'EMP0380', 0.00, 'full-time', 'permanent', true, 'Main Factory'),
('LUNTU', 'NAYIPHI', 'LOOMS', '381', 'EMP0381', 28.79, 'full-time', 'permanent', true, 'Main Factory'),
('SANELE', 'MHE', 'PRINTING', '382', 'EMP0382', 18.54, 'full-time', 'permanent', true, 'Main Factory'),
('NOSIPHIWO', 'YENANI', 'LOOMS', '383', 'EMP0383', 0.00, 'full-time', 'permanent', true, 'Main Factory'),
('SISIPHO', 'DLILANGA', 'LOOMS', '384', 'EMP0384', 0.00, 'full-time', 'permanent', true, 'Main Factory'),
('MAKEDISI', 'NOZIZWE', 'UNIT 6', '387', 'EMP0387', 21.80, 'full-time', 'permanent', true, 'Main Factory'),
('BONGOLWETHU', 'MNGENI', 'LOOMS', '390', 'EMP0390', 0.00, 'full-time', 'permanent', true, 'Main Factory'),
('TEMBA', 'LANDE', 'HYSTER DRIVER', '425', 'EMP0425', 27.14, 'full-time', 'permanent', true, 'Main Factory'),
('RESTY', 'SALENGA', 'TECH LOOMS', '427', 'EMP0427', 94.00, 'full-time', 'permanent', true, 'Main Factory'),
('ELIJAH', 'MUZUNGA', 'TECH LOOMS', '430', 'EMP0430', 55.00, 'full-time', 'permanent', true, 'Main Factory')
ON CONFLICT (atg_clock_number) DO NOTHING;