// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://znimchgnvrxpgybqnolj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpuaW1jaGdudnJ4cGd5YnFub2xqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE2NjI5MDcsImV4cCI6MjA2NzIzODkwN30.AcMTFgSPj2c74GfbNKfYsIzy7boHbiwD0V6-01Ocdv4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});